2013-03-31 17:35:35.899 [IPEngineApp] Loading url_file u'/Users/fabrizio/.ipython/profile_default/security/ipcontroller-engine.json'
2013-03-31 17:35:35.913 [IPEngineApp] Registering with controller at tcp://127.0.0.1:57949
2013-03-31 17:35:36.021 [IPEngineApp] Using existing profile dir: u'/Users/fabrizio/.ipython/profile_default'
2013-03-31 17:35:36.023 [IPEngineApp] Running file in user namespace: /Users/fabrizio/.ipython/profile_default/startup/00_math_import.py
2013-03-31 17:35:37.509 [IPEngineApp] Running file in user namespace: /Users/fabrizio/.ipython/profile_default/startup/01_debug.py
2013-03-31 17:35:37.510 [IPEngineApp] Completed registration with id 0
2013-03-31 17:56:37.580 [IPEngineApp] Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/IPython/zmq/ipkernel.py", line 189, in dispatch_control
    handler(self.control_stream, idents, msg)
  File "/usr/local/lib/python2.7/site-packages/IPython/zmq/ipkernel.py", line 618, in abort_request
    self.abort_queues()
AttributeError: 'Kernel' object has no attribute 'abort_queues'
2013-03-31 19:46:12.146 [IPEngineApp] Engine Interrupted, shutting down...

